name: Reuseable Workflow Example

on: 
  pull_request:
        
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        
  call-workflow-b:
    if: contains(github.head_ref, 'feature/') || contains(github.head_ref, 'release/')
    uses: charlenemckeown/WorkflowScratchpad/.github/workflows/b.yml@main
