name: Reuseable Workflow Example

on: 
  pull_request:
        
jobs:
  call-workflow-b:
    if: contains(github.head_ref, '/feature/') || contains(github.head_ref, '/release/')
    uses: charlenemckeown/WorkflowScratchpad/.github/workflows/b.yml@main
