name: Issue assignment

on:
  issues:
    types: [opened]

jobs:
  auto-assign:
    if: contains(github.event.issue.labels.*.name, 'deploy')
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ github.token }}
          assignees: ${{ github.actor }}
