# Sample action used to show some of the trickery you can do when someone raises a PR against your repo from a fork

name: InfraCI - Fork PR Validation

on:
  #Run when PR's are made to main, where the changes are in the bicep directory or this workflow file itself
  pull_request_target:
    branches: [main, develop] #only trigger for PR's to main/develop
    #paths: #only trigger for changes in the bicep file directory
      #- "bicep/*"

env:
  AZCLIVERSION: 2.29.2 #Pinning to a specific AZ CLI version for working with the AZ CLI
  
jobs:
  Validation:
    runs-on: ubuntu-latest
    steps:
      #Get the code files from the repo
      - uses: actions/checkout@v2

      - name: Job parameter check
        run: |
          echo "Actor is: ${{github.actor}}"
          echo "EventTrigger name is ${{github.event_name}}"
          echo "Ref is ${{github.ref}}"
          echo "Head Ref is ${{github.head_ref}}"
          echo "Base Ref is ${{github.base_ref}}"
          echo "PR obj is ${{toJson(github.event.pull_request)}}"
          echo "Is fork? ${{ github.event.pull_request.head.repo.fork }}"

      - name: Welcome the forker
        if: github.event.pull_request.head.repo.fork
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #PR_URL: ${{github.event.pull_request.html_url}}
        run: |
          Write-Output "Welcome Mr Forky"
          $PRId="${{ github.event.pull_request.number }}"
          
          gh pr comment $PRId --body "PR origin is from fork - thanks for the contribution!"
          
      - name: Add labels to PR that signal forked and full testing required
        if: github.event.pull_request.head.repo.fork
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $PRId="${{ github.event.pull_request.number }}"
          
          #if changes to bicep
          gh pr edit $PRId --add-label "requires-full-validation,do-not-merge"
          
          #gh pr edit $PRId --add-label do-not-merge
          
      - name: List files changed in this PR
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $PRId="${{ github.event.pull_request.number }}"
          
          $files=gh pr view $PRId --json files --jq '.files.[].path'
          
          write-output $files
  
  #This job uses secrets, and therefore cannot be run from a fork - so we must skip any jobs that use secrets
  Deploy:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    steps:
      #Get the code files from the repo
      - uses: actions/checkout@v2

      - name: Deploy
        run: |
          echo "Do a AZ DEPLOYMENT VALIDATE"
          echo "Do a AZ DEPLOYMENT WHATIF"
          echo "Do a AZ DEPLOYMENT CREATE"
