name: Called Workflow
on: 
  workflow_call:
    inputs:
      NAME:
        required: true
        type: string
      COLOUR:
        required: true
        type: string

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:

    - name: Echo inputs
      run: echo $NAME is $COLOUR!
      env:
        NAME: '["${{ inputs.NAME }}"]'
        COLOUR: '["${{ inputs.COLOUR }}"]'    
